services:
  qbittorrent:
    image: jacob0305/qbittorrent-nordvpn:latest
    container_name: qbittorrent-nordvpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8080:8080"
      - "6181:6181"
      - "6181:6181/udp"
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads
    environment:
      - NORDVPN_TOKEN=${NORDVPN_TOKEN}
      - NORDVPN_COUNTRY=${NORDVPN_COUNTRY}
      - WEBUI_PORT=${WEBUI_PORT}
      - TZ=${TZ}
    restart: unless-stopped
